FROM node:12-alpine as builder

# Create app directory
RUN mkdir -p /usr/src/webapp
WORKDIR /usr/src/webapp

ADD package.json /tmp/package.json
ADD package-lock.json /tmp/package-lock.json
RUN cd /tmp && npm install
RUN cp -a /tmp/node_modules /usr/src/webapp

# Bundle app source
ADD . /usr/src/webapp
RUN npm run build

CMD ["npm", "run", "server"]